language: node_js

node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"

env:
  - DIALECT=mysql
  - DIALECT=postgres

services:
  - mysql
  - postgresql

before_script:
  - mysql -uroot -e "DELETE FROM mysql.db WHERE Db = 'test\\_%';"
  - mysql -uroot -e "DELETE FROM mysql.user WHERE Host = 'localhost' AND User = '';"
  - mysql -uroot -e "FLUSH PRIVILEGES;"
  - mysql -uroot -e 'CREATE DATABASE streamer_test;'
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON streamer_test.* TO 'streamer'@'localhost' IDENTIFIED BY 'streamer1234';"
  - mysql -uroot -e "DELETE FROM mysql.user WHERE User = 'travis';"
  - mysql -uroot -e "FLUSH PRIVILEGES;"
  - psql -U postgres -c 'CREATE DATABASE streamer_test;'
  - psql -U postgres -c "CREATE USER streamer PASSWORD 'streamer';"
  - psql -U postgres -c 'CREATE ROLE streamer_role;'
  - psql -U postgres -c 'GRANT streamer_role TO streamer;'
  - psql -U postgres -c 'GRANT ALL ON DATABASE streamer_test TO streamer_role;'