language: node_js

node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"

services:
  - mysql
  - postgresql

before_script:
  - mysql -uroot -e 'CREATE DATABASE streamer_test;'
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON streamer_test.* TO 'streamer'@'localhost' IDENTIFIED BY 'streamer1234';"
  - mysql -uroot -e "FLUSH PRIVILEGES;"
  - psql -U postgres -c 'CREATE DATABASE streamer_test;'
  - psql -U postgres -c "CREATE USER streamer PASSWORD 'streamer';"
  - psql -U postgres -c 'CREATE ROLE streamer_role;'
  - psql -U postgres -c 'GRANT streamer_role TO streamer;'
  - psql -U postgres -c 'GRANT ALL ON DATABASE streamer_test TO streamer_role;'

matrix:
  fast_finish: true
  include:
    - node_js: "0.12"
      script: "npm run codeclimate"
  allow_failures:
    - node_js: "0.12"
      script: "npm run codeclimate"